CREATE TABLE EMPRESTIMO 
( 
 Id INT PRIMARY KEY AUTO_INCREMENT,  
 idFILME INT,  
 DataEmprestimo DATE NOT NULL,  
 DataDevolucao DATE NOT NULL,  
 idCLIENTE INT,  
); 

CREATE TABLE CLIENTE 
( 
 Id INT PRIMARY KEY AUTO_INCREMENT,  
 Telefone INT,  
 Nome VARCHAR(n) NOT NULL,  
 Endereco VARCHAR(n),  
); 

CREATE TABLE FILME 
( 
 Id INT PRIMARY KEY AUTO_INCREMENT,  
 Titulo VARCHAR(n) NOT NULL,  
 idCATEGORIA INT,  
 idATOR INT,  
); 

CREATE TABLE ATOR 
( 
 Id INT PRIMARY KEY AUTO_INCREMENT,  
 dtNascimento DATE NOT NULL,  
 nomePopular VARCHAR(n) NOT NULL,  
 nomeArtistico VARCHAR(n) NOT NULL,  
); 

CREATE TABLE CATEGORIA 
( 
 Id INT PRIMARY KEY AUTO_INCREMENT,  
 Nome VARCHAR(n) NOT NULL,  
); 

ALTER TABLE EMPRESTIMO ADD FOREIGN KEY(idFILME) REFERENCES FILME (Id)
ALTER TABLE EMPRESTIMO ADD FOREIGN KEY(idCLIENTE) REFERENCES CLIENTE (Id)
ALTER TABLE FILME ADD FOREIGN KEY(idCATEGORIA) REFERENCES CATEGORIA (Id)
ALTER TABLE FILME ADD FOREIGN KEY(idATOR) REFERENCES ATOR (Id)
